version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    environment:
      GO111MODULE: "on"
    working_directory: /go/src/github.com/nicholasjackson/fake-service
    steps:
      - checkout
      - run: 
          name: test application
          command: go test -v ./... 
      - run: 
          name: build application
          command: CGO_ENABLED=0 GOOS=linux go build -o bin/fake-service
      - persist_to_workspace:
          root: /go/src/github.com/nicholasjackson
          paths:
            - fake-service
  
  release:
    docker:
      - image: circleci/golang:1.12
    environment:
      GO111MODULE: "on"
    working_directory: /go/src/github.com/nicholasjackson/fake-service
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /go/src/github.com/nicholasjackson
      - run: 
         name: docker login
         command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run: 
         name: docker build
         command: docker build -t nicholasjackson/fake-service:${CIRCLE_TAG} .
      - run: 
          name: docker push
          command: docker push nicholasjackson/fake-service:${CIRCLE_TAG}

workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
